status/urls.py
from django.urls import re_path, include
from django.views.decorators.cache import cache_page
from tastypie.api import NamespacedApi
from status.api import IncidentResource, StatusResource
from status.models import Incident
from status.views import (
    DashboardView, HomeView, IncidentArchiveMonthView, IncidentArchiveYearView, IncidentDeleteView,
    IncidentDetailView, IncidentUpdateUpdateView, create_incident, IncidentHideView, HiddenDashboardView
)


v1_api = NamespacedApi(api_name='v1', urlconf_namespace='status')
v1_api.register(StatusResource())
v1_api.register(IncidentResource())


urlpatterns = [
    re_path(r'^api/', include(v1_api.urls)),
    re_path(r'^$', cache_page(15)(HomeView.as_view()), name='home'),
    re_path(r'^dashboard/$', DashboardView.as_view(), name='dashboard'),
    re_path(r'^dashboard/hidden/$', HiddenDashboardView.as_view(), name='dashboard_hidden'),
    re_path(r'^incident/new/$', create_incident, name='incident_create'),
    re_path(r'^incident/(?P<pk>\d+)/$', IncidentDetailView.as_view(model=Incident), name='incident_detail'),
    re_path(r'^incident/(?P<pk>\d+)/update/$', IncidentUpdateUpdateView.as_view(), name='incident_update'),
    re_path(r'^incident/(?P<pk>\d+)/hide/$', IncidentHideView.as_view(), name='incident_hide'),
    re_path(r'^incident/(?P<pk>\d+)/delete/$', IncidentDeleteView.as_view(), name='incident_delete'),
    re_path(r'^archive/(?P<year>\d{4})/$', IncidentArchiveYearView.as_view(), name="archive_year"),
    re_path(
        r'^archive/(?P<year>\d{4})/(?P<month>\d+)/$',
        IncidentArchiveMonthView.as_view(month_format='%m'),
        name="archive_month_numeric"
    ),
]

app_name = 'status'

statuspage/urls.py
from django.conf import settings
from django.urls import re_path, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
# from django.contrib.auth.views import login, logout
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView, ListView, DetailView


admin.autodiscover()
urlpatterns = [
    re_path(r'^', include('status.urls', namespace='status')),
    re_path(r'^account/login/$', LoginView.as_view, {'template_name': 'admin/login.html'}, 'login'),
    re_path(r'^account/logout/$', LogoutView.as_view, {'template_name': 'admin/logout.html'}, 'logout'),
    re_path(r'^avatar/', include('avatar.urls')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^admin/doc/', include('django.contrib.admindocs.urls')),
]

app_name = 'status'

# if settings.DEBUG:
#     urlpatterns += url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
#         'document_root': settings.MEDIA_ROOT,
#     }),
#     urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ]

status/models.py
from django.conf import settings
from django.urls import reverse
from django.db import models
from django.utils import timezone


STATUS_CHOICES = (
    ('success', 'Success'),
    ('info', 'Information'),
    ('warning', 'Warning'),
    ('danger', 'Danger'),
)


class BaseModel(models.Model):
    """ BaseModel provides information on creation and modification times for all child objects. """
    created = models.DateTimeField(editable=False, blank=True, null=True)
    updated = models.DateTimeField(editable=False, blank=True, null=True)

    def save(self, *args, **kwargs):
        """ Save an object and note the created or updated time. """
        if not self.pk:
            self.created = timezone.now()
        self.updated = timezone.now()
        super(BaseModel, self).save(*args, **kwargs)

    class Meta:
        abstract = True


class Status(BaseModel):
    """ Status of an incident or event """
    name = models.CharField(max_length=50)
    type = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Information')
    icon = models.CharField(max_length=255, help_text='Font Awesome icon name', default='fa-warning')

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = 'Status'
        verbose_name_plural = 'Statuses'


class Incident(BaseModel):
    """ Creates an incident.  Incidents are displayed at the top of the page until closed. """
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=255)
    hidden = models.BooleanField(default=False)

    def __unicode__(self):
        return "%s - %s" % (self.user, self.name)

    def get_absolute_url(self):
        return reverse('status:incident_detail', args=[self.pk, ])

    def get_first_update(self):
        try:
            first = self.incidentupdate_set.first()
        except IncidentUpdate.DoesNotExist:
            first = None
        return first

    def get_latest_update(self):
        try:
            latest = self.incidentupdate_set.latest()
        except IncidentUpdate.DoesNotExist:
            latest = None
        return latest

    class Meta:
        get_latest_by = 'created'
        verbose_name = 'Incident'
        verbose_name_plural = 'Incidents'
        ordering = ['-created', ]


class IncidentUpdate(BaseModel):
    """ Updates about an incident. """
    incident = models.ForeignKey(Incident, on_delete=models.DO_NOTHING)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING)
    status = models.ForeignKey(Status, on_delete=models.DO_NOTHING)
    description = models.TextField()

    def __unicode__(self):
        return "%s - %s: %s" % (self.user, self.status, self.description)

    def get_absolute_url(self):
        return reverse('status:incident_detail', args=[self.incident.pk, ])

    class Meta:
        get_latest_by = 'created'
        verbose_name = 'Incident Update'
        verbose_name_plural = 'Incident Updates'
        ordering = ['created', ]

    def save(self, *args, **kwargs):
        """ Update the parent incident update time too. """
        self.incident.updated = timezone.now()
        self.incident.save()
        super(IncidentUpdate, self).save(*args, **kwargs)

status/forms.py
from django import forms
from status.models import Incident, IncidentUpdate
from braces.forms import UserKwargModelFormMixin

import logging
logger = logging.getLogger(__name__)


class IncidentUpdateCreateForm(forms.ModelForm):
    class Meta:
        model = IncidentUpdate
        fields = ['status', 'description']


class IncidentCreateForm(forms.ModelForm):
    class Meta:
        model = Incident
        fields = ['name']

status/views.py
from datetime import date, timedelta
from django.conf import settings
from django.contrib.sites.shortcuts import get_current_site
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.template import RequestContext, Template
from django.template.loader import get_template
from django.utils.decorators import method_decorator
from django.views.generic import (
    MonthArchiveView, YearArchiveView, CreateView, DeleteView, DetailView, ListView, TemplateView
)
from stronghold.decorators import public
from status.models import Incident, IncidentUpdate
from status.forms import IncidentCreateForm, IncidentUpdateCreateForm

from opentelemetry import trace
from opentelemetry.exporter.jaeger.thrift import JaegerExporter
from opentelemetry.sdk.resources import SERVICE_NAME, Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor


# from opentelemetry.sdk.trace.export import (
#     ConsoleSpanExporter,
#     SimpleSpanProcessor,
# )

trace.set_tracer_provider(
    TracerProvider(
       resource=Resource.create({SERVICE_NAME: "StatusPage"}) 
    )
)

tracer = trace.get_tracer(__name__)

jaeger_exporter = JaegerExporter(
    #service_name="my-helloworld-service",
    agent_host_name="localhost",
    agent_port=6831,
)

# Create a BatchSpanProcessor and add the exporter to it
span_processor = BatchSpanProcessor(jaeger_exporter)

trace.get_tracer_provider().add_span_processor(span_processor)

            
import slack
import slack.chat
import logging
logger = logging.getLogger(__name__)


def send_to_slack(message, channel='engineering', username='statusbot', emoji=':statusbot:', override_debug=False):
    with tracer.start_as_current_span("server_request"):
        slack.api_token = settings.SLACK_TOKEN
        if settings.DEBUG and not override_debug:
            logger.info('Diverting from %s to dev while in debug mode as %s: %s' % (channel, username, message))
            slack.chat.post_message('dev', 'DEBUG: ' + message, username=username, icon_emoji=emoji)
        else:
            logger.info('Sending to channel %s as %s: %s' % (channel, username, message))
            slack.chat.post_message(channel, message, username=username, icon_emoji=emoji)


def create_incident(request):
    with tracer.start_as_current_span("server_request"):
        if request.method == 'POST':
            form = IncidentCreateForm(request.POST)
            form2 = IncidentUpdateCreateForm(request.POST)
            if form.is_valid() and form2.is_valid():
                i = form.save(commit=False)
                i.user = request.user
                print(i)
                i.save()

                f = form2.save(commit=False)
                f.incident = i
                f.user = request.user
                f.save()

                if settings.SLACK_CHANNEL and settings.SLACK_TOKEN:
                    if len(f.description) > 50:
                        description = f.description[:50] + '...'
                    else:
                        description = f.description
                    try:
                        message = "<https://%s%s|%s> (%s): %s" % (
                            get_current_site(request),
                            reverse('status:incident_detail', args=[i.pk, ]),
                            i.name,
                            f.status.name,
                            description
                        )
                        send_to_slack(message, username=settings.SLACK_USERNAME, channel=settings.SLACK_CHANNEL)
                    except Exception as e:
                        logger.warn('Unable to send to slack: %s' % (e))

                return HttpResponseRedirect('/')
        else:
            form = IncidentCreateForm()
            form2 = IncidentUpdateCreateForm()
        
        request_context = RequestContext(request)
        request_context.push({'form': form, 'form2': form2})
        t = get_template('status/incident_create_form.html')
        rendered_template = t.render(request_context.flatten(), request)
        return HttpResponse(rendered_template)
        #return get_template('status/incident_create_form.html').render(request_context.flatten(), request)

        #return render(request, template_name='status/incident_create_form.html', context=request_context)


class DashboardView(ListView):
    model = Incident

    def get_queryset(self):
        return Incident.objects.exclude(hidden=True)


class HiddenDashboardView(ListView):
    model = Incident


class IncidentHideView(DeleteView):
    model = Incident
    template_name = 'status/incident_hide.html'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.hidden = True
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('status:dashboard')


class IncidentDeleteView(DeleteView):
    model = Incident

    def get_success_url(self):
        return reverse('status:dashboard')


class IncidentUpdateUpdateView(CreateView):
    model = IncidentUpdate
    form_class = IncidentUpdateCreateForm
    template_name = 'status/incident_form.html'

    def get_success_url(self):
        return reverse('status:incident_detail', args=[self.kwargs['pk']])

    def form_valid(self, form):
        iu = form.save(commit=False)
        i = Incident.objects.get(pk=self.kwargs['pk'])
        i.hidden = False
        i.save()
        iu.incident = i
        iu.incident.hidden = False
        iu.incident.save()
        iu.user = self.request.user
        iu.save()
        return HttpResponseRedirect(self.get_success_url())


class IncidentDetailView(DetailView):
    model = Incident

    @method_decorator(public)
    def dispatch(self, *args, **kwargs):
        return super(IncidentDetailView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(IncidentDetailView, self).get_context_data(**kwargs)
        context.update({
            'form': IncidentUpdateCreateForm(),
        })
        return context


class IncidentArchiveYearView(YearArchiveView):
    make_object_list = True
    queryset = Incident.objects.all()
    date_field = 'updated'

    @method_decorator(public)
    def dispatch(self, *args, **kwargs):
        return super(IncidentArchiveYearView, self).dispatch(*args, **kwargs)


class IncidentArchiveMonthView(MonthArchiveView):
    make_object_list = True
    queryset = Incident.objects.all()
    date_field = 'updated'
    month_format = '%m'

    @method_decorator(public)
    def dispatch(self, *args, **kwargs):
        return super(IncidentArchiveMonthView, self).dispatch(*args, **kwargs)


class HomeView(TemplateView):
    http_method_names = ['get', ]
    template_name = 'status/home.html'

    @method_decorator(public)
    def dispatch(self, *args, **kwargs):
        return super(HomeView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        incident_list = Incident.objects.filter(hidden=False).order_by('-updated')
        context.update({
            'incident_list': incident_list
        })

        if hasattr(settings, 'STATUS_TICKET_URL'):
            context.update({'STATUS_TICKET_URL': settings.STATUS_TICKET_URL})

        if hasattr(settings, 'STATUS_LOGO_URL'):
            context.update({'STATUS_LOGO_URL': settings.STATUS_LOGO_URL})

        if hasattr(settings, 'STATUS_TITLE'):
            context.update({'STATUS_TITLE': settings.STATUS_TITLE})

        status_level = 'success'
        for incident in incident_list:
            try:
                if incident.get_latest_update().status.type == 'danger':
                    status_level = 'danger'
                    break
                elif incident.get_latest_update().status.type == 'warning':
                    status_level = 'warning'
                elif incident.get_latest_update().status.type == 'info' and not status_level == 'warning':
                    status_level = 'info'
            except AttributeError:
                # Unable to get_latest_update(), 'None' has no .status
                pass

        context.update({
            'status_level': status_level
        })
        return context

status/templates/status/home.html
{% extends "base.html" %}
{% load avatar_tags %}
{% block exthead %}
    <meta http-equiv="refresh" content="60">
{% endblock %}
{% block menubar %}
{% endblock %}

{% block content %}
    {% if STATUS_LOGO_URL %}
        <div>
            <div class="pull-right"><img src="{{ STATUS_LOGO_URL }}" /></div>
        </div>
    {% endif %}
    {% if status_level %}
        <p class="alert alert-{{ status_level }}">{% if status_level == 'success' %}There are no known issues at this time{% else %}Some systems are experiencing issues{% endif %}</p>
    {% endif %}
    {% for incident in incident_list %}
        {% include "status/partials/incident.html" with with_callout=True %}
    {% endfor %}
    {% if STATUS_TICKET_URL %}
    <div class="row">
        <div class="col-md-6">
            <p>If you are having an issue that is not listed above, please turn in a ticket!</p>
            <p><a class="btn btn-primary btn-lg" href="{{ STATUS_TICKET_URL }}" role="button"><i class="glyphicon glyphicon-pencil"></i> New Ticket!</a></p>
        </div>
    </div>
    {% endif %}
{% endblock %}

status/templates/status/incident_archive_month.html
{% extends "base.html" %}
{% load avatar_tags %}

{% block content %}
    <h1>Archive for {{ month|date:"F Y" }}</h1>
    {% if STATUS_LOGO_URL %}
    <div>
        <div class="pull-right"><img src="{{ STATUS_LOGO_URL }}" /></div>
    </div>
    {% endif %}
    <ul class="list-group components">
        {% for incident in incident_list %}
            <li class="list-group-item component">
            <h3><i class="glyphicon fa {{ incident.status.icon }}"></i> <A HREF="{% url 'status:incident_detail' incident.pk %}">{{ incident.name }}</A> <small class="text-{{ incident.status.type }}">{{ incident.status.name }}</small></h3>
                <p><div class="pull-left" style="padding-right: 10px;">{% avatar incident.user 36 %}</div><h4>{{ incident.description|linebreaksbr|urlize }}</h4></p>
                <p>Updated {{ incident.updated|timesince }} ago by {{ incident.user.username }} <A HREF="{% url 'status:incident_detail' incident.pk %}">Details</A></p>
            </li>
        {% endfor %}
    </ul>
</ul>
{% endblock %}

status/templates/status/incident_archive_year.html
{% extends "base.html" %}
{% load avatar_tags %}

{% block content %}
    <h1>Archive for {{ year|date:"Y" }}</h1>
    {% if STATUS_LOGO_URL %}
    <div>
        <div class="pull-right"><img src="{{ STATUS_LOGO_URL }}" /></div>
    </div>
    {% endif %}
    <ul class="list-group components">
        {% for incident in incident_list %}
            <li class="list-group-item component">
            <h3><i class="glyphicon fa {{ incident.status.icon }}"></i> <A HREF="{% url 'status:incident_detail' incident.pk %}">{{ incident.name }}</A> <small class="text-{{ incident.status.type }}">{{ incident.status.name }}</small></h3>
                <p><div class="pull-left" style="padding-right: 10px;">{% avatar incident.user 36 %}</div><h4>{{ incident.description|linebreaksbr|urlize }}</h4></p>
                <p>Updated {{ incident.updated|timesince }} ago by {{ incident.user.username }} <A HREF="{% url 'status:incident_detail' incident.pk %}">Details</A></p>
            </li>
        {% endfor %}
    </ul>
</ul>
{% endblock %}

status/templates/status/incident_confirm_delete.html
{% extends "base.html" %}
{% load avatar_tags %}
{% load bootstrap3 %}

{% block content %}
    <div class="alert alert-danger" role="alert">Are you sure you wish to delete the following incident?</div>

    <ul class="list-group components">
        <li class="list-group-item component">
            <h4><i class="glyphicon fa {{ incident.status.icon }}"></i> {{ incident.name }} <small class="text-{{ incident.status.type }}">{{ incident.status.name }}</small></h4>
            <p><div class="pull-left" style="padding-right: 10px;">{% avatar request.user 36 %}</div>{{ incident.description }}</p>
            <p>Updated {{ incident.updated|timesince }} ago</p>
        </li>
    </ul>
    <form action="." method="POST">
        {% csrf_token %}
        {% buttons %}
            <button type="submit" class="btn btn-danger">
                {% bootstrap_icon "remove" %} Delete
            </button>
        {% endbuttons %}
    </form>
{% endblock %}

status/templates/status/incident_create_form.html
{% extends "base.html" %}
{% load avatar_tags %}
{% load bootstrap3 %}

{% block content %}
    <form action="." method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_form form2 %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                {% bootstrap_icon "star" %} Submit
            </button>
        {% endbuttons %}
    </form>
{% endblock %}

status/templates/status/incident_detail.html
{% extends "base.html" %}
{% load avatar_tags %}
{% load bootstrap3 %}

{% block content %}
    <h2>Current Status</h2>
    {% include "status/partials/incident.html" with hide_more=True hide_detail=True with_callout=True %}
    <h2>History</h2>
    <ul class="list-group components">
        {% for update in incident.incidentupdate_set.all %}
        <div class="bs-callout bs-callout-{{ update.status.type }}">
                <li class="list-group-item component">
                <h3><i class="glyphicon fa {{ update.status.icon }}"></i> <small class="text-{{ update.status.type }}">{{ update.status.name }}</small></h3>
                    <p><div class="pull-left" style="padding-right: 10px;">{% avatar update.user 36 %}</div><h4>{{ update.description|linebreaksbr|urlize }}</h4></p>
                    <p>Posted {{ update.created|timesince }} ago by {{ update.user.username }}</p>
                </li>
            </div>
        {% endfor %}
    </ul>
    {% if request.user.is_authenticated %}
    <form action="{% url 'status:incident_update' incident.pk %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">
                    {% bootstrap_icon "star" %} Submit
                </button>
            {% endbuttons %}
        </form>
    {% endif %}
{% endblock %}

status/templates/status/incident_form.html
{% extends "base.html" %}
{% load avatar_tags %}
{% load bootstrap3 %}

{% block content %}
    <form action="." method="POST">
        {% csrf_token %}
            {% bootstrap_form form %}
            {% if inlines %}
                {% for f in inlines %}
                    {% bootstrap_formset f %}
                {% endfor %}
        {% endif %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                {% bootstrap_icon "star" %} Submit
            </button>
        {% endbuttons %}
    </form>
{% endblock %}

status/templates/status/incident_hide.html
{% extends "base.html" %}
{% load avatar_tags %}
{% load bootstrap3 %}

{% block content %}
    <div class="alert alert-warning" role="alert">Are you sure you wish to hide the following incident? It will no longer be shown on the home page, but will be accessible to users.</div>

    <ul class="list-group components">
        <li class="list-group-item component">
            <h4><i class="glyphicon fa {{ incident.status.icon }}"></i> {{ incident.name }} <small class="text-{{ incident.status.type }}">{{ incident.status.name }}</small></h4>
            <p><div class="pull-left" style="padding-right: 10px;">{% avatar request.user 36 %}</div>{{ incident.description }}</p>
            <p>Updated {{ incident.updated|timesince }} ago</p>
        </li>
    </ul>
    <form action="." method="POST">
        {% csrf_token %}
        {% buttons %}
            <button type="submit" class="btn btn-danger">
                {% bootstrap_icon "eye-close" %} Hide
            </button>
        {% endbuttons %}
    </form>
{% endblock %}

status/templates/status/incident_list.html
{% extends "base.html" %}

{% block content %}
    <table class="table table-condensed table-bordered table-striped table-hover">
        <thead>
            <tr>
                <td>ID</td>
                <td>Created</td>
                <td>Updated</td>
                <td>User</td>
                <td>Name</td>
                <td>Status</td>
                <td>Visible</td>
                <td>Description</td>
                <td>Actions</td>
            </tr>
        </thead>
        <tbody>
            {% for incident in incident_list %}
                <tr>
                    <td><A HREF="{% url 'status:incident_detail' incident.pk %}">{{ incident.pk }}</A></td>
                    <td>{{ incident.created }} ({{ incident.created|timesince }} ago)</td>
                    <td>{{ incident.updated }} ({{ incident.updated|timesince }} ago)</td>
                    <td>{{ incident.user.username }}</td>
                    <td>{{ incident.name }}</td>
                    <td>{{ incident.get_latest_update.status.name }}</td>
                    <td>
                        {% if incident.hidden %}
                            <i class="fa fa-times" style="color: #FF0000;"></i>
                        {% else %}
                            <i class="fa fa-thumbs-o-up" style="color: #00FF00;"></i>
                        {% endif %}
                    </td>
                    <td>{{ incident.get_latest_update.description|truncatewords:25 }}</td>
                    <td>
                        <A class="btn btn-primary btn-xs" HREF="{% url 'status:incident_update' incident.pk %}">Update</A>
                        {% if not incident.hidden %}<A class="btn btn-primary btn-xs" HREF="{% url 'status:incident_hide' incident.pk %}">Hide</A>{% endif %}
                        <A class="btn btn-danger btn-xs" HREF="{% url 'status:incident_delete' incident.pk %}">Delete</A>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}